"""
Dataset loading and integrity verification for the SCAPS-1D solar cell
dataset.

The raw file is a full-factorial grid: 5 (HTL) x 8 (Absorber) x 5 (ETL)
x 5 (N_A) x 5 (N_D) = 5000 rows, generated by a deterministic
drift-diffusion simulator. This module is the single source of truth
for:

  - which columns are inputs vs. outputs (INPUT_COLS / OUTPUT_COLS)
  - loading + cleaning quirks in the raw Excel export
  - the integrity checks that justify every downstream physics claim
    (no noise, no duplicates, full grid coverage, PCE self-consistency)

Known raw-file quirks (discovered by inspection, handled here so no
other module has to know about them):

  1. Trailing whitespace on the six output-column headers
     (e.g. "PCE (%)                      ").
  2. N_A and N_D are read by pandas/openpyxl as Python object dtype
     containing arbitrary-precision Python ints (values like
     5.0e19 exceed float32 precision needs but openpyxl still emits
     them as big ints rather than floats). They must be explicitly
     cast to float64 before any numeric use.
"""

from __future__ import annotations

import math
from dataclasses import dataclass, field
from pathlib import Path

import numpy as np
import pandas as pd

# ---------------------------------------------------------------------
# Schema
# ---------------------------------------------------------------------

INPUT_COLS: list[str] = [
    "HTL thickness (μm)",
    "Absorber Thickness (μm)",
    "ETL thickness (μm)",
    "N_A (1/cm3)",
    "N_D (1/cm3)",
]

OUTPUT_COLS: list[str] = [
    "PCE (%)",
    "Voc (V)",
    "Jsc (mA/cm2)",
    "FF (%)",
    "V_MPP (V)",
    "J_MPP (mA/cm2)",
]

# Columns whose physical scale spans multiple decades and which
# therefore need a log10 transform before use in any distance-based
# or kernel-based model (see features.py).
LOG_SCALE_COLS: list[str] = ["N_A (1/cm3)", "N_D (1/cm3)"]

# (lower, upper) physical bounds used by the sanity checks. `None`
# means "no upper/lower bound checked here".
PHYSICALITY_BOUNDS: dict[str, tuple[float | None, float | None]] = {
    "Voc (V)": (0.0, 2.0),
    "Jsc (mA/cm2)": (0.0, 45.0),
    "FF (%)": (0.0, 100.0),
    "PCE (%)": (0.0, 100.0),
}

DEFAULT_RAW_PATH = Path(__file__).resolve().parents[2] / "data" / "raw" / "SOLAR_DATASET.xlsx"

# Standard test conditions (AM1.5G, 1-sun) used by the simulator.
P_IN_MW_CM2 = 100.0


# ---------------------------------------------------------------------
# Loading
# ---------------------------------------------------------------------

def load_dataset(path: str | Path = DEFAULT_RAW_PATH) -> pd.DataFrame:
    """Load and clean the raw SCAPS-1D dataset.

    This function never writes to `path`; it only reads. Cleaning is
    limited to whitespace-stripping column names and casting N_A/N_D
    to float64 -- no rows are dropped or reordered, so the returned
    frame is a faithful, analysis-ready copy of the raw file.

    Parameters
    ----------
    path:
        Path to the raw .xlsx file. Defaults to data/raw/SOLAR_DATASET.xlsx
        relative to the repository root.

    Returns
    -------
    pd.DataFrame
        Cleaned dataframe with INPUT_COLS + OUTPUT_COLS columns.
    """
    path = Path(path)
    if not path.exists():
        raise FileNotFoundError(
            f"Raw dataset not found at {path}. Place the original "
            f"SOLAR_DATASET.xlsx there (see data/README.md)."
        )

    df = pd.read_excel(path)
    df.columns = df.columns.str.strip()

    missing = [c for c in INPUT_COLS + OUTPUT_COLS if c not in df.columns]
    if missing:
        raise ValueError(
            f"Loaded file is missing expected columns: {missing}. "
            f"Found columns: {list(df.columns)}"
        )

    # N_A / N_D arrive as object dtype (big Python ints) from openpyxl;
    # cast explicitly so every downstream numeric op is well-defined.
    for col in LOG_SCALE_COLS:
        df[col] = df[col].astype(np.float64)

    # Defensive: make sure everything else is numeric too.
    for col in INPUT_COLS + OUTPUT_COLS:
        if not pd.api.types.is_numeric_dtype(df[col]):
            df[col] = pd.to_numeric(df[col])

    return df[INPUT_COLS + OUTPUT_COLS].copy()


# ---------------------------------------------------------------------
# Integrity verification
# ---------------------------------------------------------------------

@dataclass
class IntegrityReport:
    """Structured result of `verify_dataset_integrity`.

    `ok` is True iff every check that is marked as a hard requirement
    passed. Soft/informational findings (e.g. exact factorial level
    values) are always included in `details` regardless of `ok`.
    """

    n_rows: int
    n_missing_values: int
    n_duplicate_rows: int
    n_duplicate_input_combos: int
    level_counts: dict[str, int]
    is_full_factorial: bool
    n_distinct_combos: int
    expected_combos: int
    pce_identity_max_abs_error: float
    pce_identity_mean_abs_error: float
    n_physicality_violations: dict[str, int]
    n_na_exceeds_nd: int
    ok: bool
    failures: list[str] = field(default_factory=list)

    def summary(self) -> str:
        lines = [
            f"rows: {self.n_rows}",
            f"missing values: {self.n_missing_values}",
            f"duplicate rows: {self.n_duplicate_rows}",
            f"duplicate input combos: {self.n_duplicate_input_combos}",
            f"levels per input: {self.level_counts}",
            f"full factorial ({self.expected_combos} expected combos): "
            f"{self.is_full_factorial} ({self.n_distinct_combos} distinct combos)",
            f"PCE identity max |error|: {self.pce_identity_max_abs_error:.3e}",
            f"PCE identity mean |error|: {self.pce_identity_mean_abs_error:.3e}",
            f"physicality violations: {self.n_physicality_violations}",
            f"rows with N_A > N_D: {self.n_na_exceeds_nd}",
            f"OK: {self.ok}",
        ]
        if self.failures:
            lines.append("FAILURES:")
            lines.extend(f"  - {f}" for f in self.failures)
        return "\n".join(lines)


def verify_dataset_integrity(
    df: pd.DataFrame,
    pce_error_tolerance: float = 1e-3,
) -> IntegrityReport:
    """Run the integrity checks that every downstream methodology claim
    (no noise, complete grid, physical consistency) depends on.

    This is deliberately cheap (no model fitting) so it is safe to run
    on every load, including in CI.

    Parameters
    ----------
    df:
        Output of `load_dataset`.
    pce_error_tolerance:
        Max allowed |PCE_reported - PCE_implied| (percentage points)
        before flagging a row as inconsistent. Default is generous
        relative to the observed floating-point-level error (~1e-6).
    """
    failures: list[str] = []

    n_rows = len(df)

    n_missing = int(df[INPUT_COLS + OUTPUT_COLS].isna().sum().sum())
    if n_missing != 0:
        failures.append(f"{n_missing} missing values found")

    n_dup_rows = int(df.duplicated().sum())
    n_dup_combos = int(df.duplicated(subset=INPUT_COLS).sum())
    if n_dup_combos != 0:
        failures.append(f"{n_dup_combos} duplicate input combinations found")

    level_counts = {c: int(df[c].nunique()) for c in INPUT_COLS}
    expected_combos = math.prod(level_counts.values())

    combo_sizes = df.groupby(INPUT_COLS).size()
    n_distinct_combos = int(len(combo_sizes))
    is_full_factorial = bool(
        n_distinct_combos == expected_combos
        and (combo_sizes == 1).all()
        and n_rows == expected_combos
    )
    if not is_full_factorial:
        failures.append(
            f"dataset is not a complete full factorial grid "
            f"(expected {expected_combos} unique combos each appearing once, "
            f"found {n_distinct_combos} distinct combos over {n_rows} rows)"
        )

    pce_implied = (
        df["Voc (V)"] * df["Jsc (mA/cm2)"] * (df["FF (%)"] / 100.0)
    ) / P_IN_MW_CM2 * 100.0
    pce_error = (pce_implied - df["PCE (%)"]).abs()
    max_err = float(pce_error.max())
    mean_err = float(pce_error.mean())
    if max_err > pce_error_tolerance:
        failures.append(
            f"PCE identity violated: max |error| {max_err:.3e} exceeds "
            f"tolerance {pce_error_tolerance:.3e}"
        )

    physicality_violations: dict[str, int] = {}
    for col, (lo, hi) in PHYSICALITY_BOUNDS.items():
        below = int((df[col] < lo).sum()) if lo is not None else 0
        above = int((df[col] > hi).sum()) if hi is not None else 0
        physicality_violations[col] = below + above
        if below or above:
            failures.append(
                f"{col}: {below} rows below {lo}, {above} rows above {hi}"
            )

    n_na_exceeds_nd = int((df["N_A (1/cm3)"] > df["N_D (1/cm3)"]).sum())
    # Not currently a hard failure: within the tested grid this is
    # expected to be 0 (N_A range is strictly below N_D range), which
    # means the "N_A <= N_D" physical constraint referenced in the BO
    # methodology is *never active* inside these bounds. That is worth
    # knowing, not worth failing a build over.

    ok = len(failures) == 0

    return IntegrityReport(
        n_rows=n_rows,
        n_missing_values=n_missing,
        n_duplicate_rows=n_dup_rows,
        n_duplicate_input_combos=n_dup_combos,
        level_counts=level_counts,
        is_full_factorial=is_full_factorial,
        n_distinct_combos=n_distinct_combos,
        expected_combos=expected_combos,
        pce_identity_max_abs_error=max_err,
        pce_identity_mean_abs_error=mean_err,
        n_physicality_violations=physicality_violations,
        n_na_exceeds_nd=n_na_exceeds_nd,
        ok=ok,
        failures=failures,
    )


def get_level_grid(df: pd.DataFrame) -> dict[str, np.ndarray]:
    """Return the sorted unique levels tested for each input parameter."""
    return {c: np.sort(df[c].unique()) for c in INPUT_COLS}


if __name__ == "__main__":
    # Lightweight manual check: `python -m solar_gpr.data`
    frame = load_dataset()
    report = verify_dataset_integrity(frame)
    print(report.summary())
